services:
  - name: blockdag-backend
    type: web
    builder: NIXPACKS
    build:
      command: |
        pip install -r requirements.txt
        python scripts/init_db.py
        python scripts/load_data.py
    start:
      command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    env:
      PYTHON_VERSION: 3.12