services:
  - type: web
    name: blockdag-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python scripts/init_db.py
      python scripts/load_data.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12