name: Code Linting

on:
  push:
    branches:
      - master
      - develop
  pull-request:
    branches:
      - master
      - develop


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python linting dependencies
        run: pip install flake8

      - name: Lint Python in backend
        run: flake8 backend/

      - name: Set up node js for frontend and contracts
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: Install solidity linter (solhint)
        run: npm install -g solhint

      - name: Lint Solidity in contracts 
        run: solhint 'contacts/**/*.sol'

      - name: Install Next.js frontend dependencies
        working-directory: frontend/
        run: npm install

      - name: Lint next.js in frontend
        working-directory: frontend/
        run: npm run lint
